-- creating database

create database ola_database;

-- creating table booking

CREATE TABLE BOOKINGS (
	DATE TIMESTAMP,
	TIME TIME,
	BOOKING_ID VARCHAR(50),
	BOOKING_STATUS VARCHAR(50),
	CUSTOMER_ID VARCHAR(50),
	VEHICLE_TYPE VARCHAR(50),
	PICKUP_LOCATION VARCHAR(50),
	DROP_LOCATION VARCHAR(50),
	V_TAT INT,
	C_TAT INT,
	CANCELED_RIDES_BY_CUSTOMER VARCHAR(50),
	CANCELED_RIDES_BY_DRIVER VARCHAR(50),
	INCOMPLETE_RIDES VARCHAR(50),
	INCOMPLETE_RIDES_REASON VARCHAR(50),
	BOOKING_VALUE INT,
	PAYMENT_METHOD VARCHAR(50),
	RIDE_DISTANCE INT,
	DRIVER_RATINGS DECIMAL,
	CUSTOMER_RATING DECIMAL
);

-- Loaded data using import